### ISSUE TITLE
Random error on unmount : Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [react-component/trigger#322]
### Actions
We have an antd slider mounted on a Lazy loaded page (with a `Suspense` parent).
When we click in the menu of our website, this unmount the current lazy loaded page and load an other lazy loaded page. (Using react router component `Route`)
During this operation, we sometime have an error popping on `rc-trigger` library.

Is there any way to protect against this ?

### Error
```
Error: Unable to find node on an unmounted component.
  at a(webpack://lcdp-react/../node_modules/react-dom/cjs/react-dom.production.min.js:56:67)
  at Zb(webpack://lcdp-react/../node_modules/react-dom/cjs/react-dom.production.min.js:57:217)
  at exports.findDOMNode(webpack://lcdp-react/../node_modules/react-dom/cjs/react-dom.production.min.js:320:226)
  at getRootDomNode(webpack://lcdp-react/../node_modules/rc-trigger/lib/index.js:255:34)
  at attachParent(webpack://lcdp-react/../node_modules/rc-trigger/lib/index.js:349:29)
  at _this.attachId(webpack://lcdp-react/../node_modules/rc-trigger/lib/index.js:367:19)
  at callRef(webpack://lcdp-react/../node_modules/rc-trigger/node_modules/rc-util/lib/raf.js:35:7)
  at realId(webpack://lcdp-react/../node_modules/rc-trigger/node_modules/rc-util/lib/raf.js:39:9)
  at s(webpack://lcdp-react/../src/helpers.ts:98:1)
```

### Context
rc-trigger version : 5.3.4
antd version : 4.17.3

Yours faithfully,
LCDP

**Comment by ericdong79** [comment]
Same issue here (Ant Design 4.18 + React 17), any updates?

**Comment by zzuhan** [comment]
same issue (rc-trigger 5.2.10，Ant Design 4.18.3)
